# Generated by Django 4.1.4 on 2023-01-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagline',
            field=models.TextField(default=''),
        ),
    ]
