# Generated by Django 4.1.4 on 2022-12-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='#550C18', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='secondary_color',
            field=models.CharField(default='#8F1429', max_length=7),
            preserve_default=False,
        ),
    ]
